name: Grove Conflict Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: NathanDrake2406/grove/action@feat-github-action
        with:
          grove-version: "v0.4.0-rc.1"
          base-branch: main
          comment-on-clean: "true"
